name: conditional_import
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_hooks: ^0.11.0
  hooks_riverpod: ^0.11.1
  flutter_midi: ^1.0.2
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
